
stages:
  - build
  - test
  - push

variables:
  REGISTRY_GROUP_PROJECT: $CI_REGISTRY/git-training/calculator

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build-image:
  stage: build
  script:
    - docker build . --tag $REGISTRY_GROUP_PROJECT/calculator:latest
    
test-image:
  stage: test
  script:
    - echo Insert fancy API test here!

push-image:
  stage: push
  script:
- docker push $REGISTRY_GROUP_PROJECT/calculator:latest